### ISSUE TITLE
results not reproducable

### ISSUE THREAD

**Issue by xiaziyna** [Evidlo/expsweep#1]
![test1](https://user-images.githubusercontent.com/79553716/177633043-c059f1b2-19fa-4563-8d78-4c352b54ab7c.png)
As you can see this python library is flawed as I could not reproduce the figure.
Please fix it immediately.
Sincerely,
your colleague.

**Comment by Evidlo** [comment]
Dear @xiaziyna,

It's clear that there is some confusion here about the purpose of the library.  Perhaps you should ask your husband, father or male friend for some assistance?

Evidlo

**Comment by xiaziyna** [comment]
I asked them but they told me it's best if I just don't use a computer
anymore and thus I am writing this message via carrier pigeon.
