### ISSUE TITLE
no issue, just wanted to show off my animation

### ISSUE THREAD

**Issue by xiaziyna** [Evidlo/expsweep#2]
https://user-images.githubusercontent.com/79553716/178054711-6e0890fc-4ab6-4e95-949d-0b51af17b9b1.mp4

**Comment by Evidlo** [comment]
![Creeper_(Minecraft)](https://user-images.githubusercontent.com/5455841/178842362-e7ac9357-dd86-43e0-ae21-dd191bc827ed.png)
